name: Docker Image CI
on:
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Get the version
        id: vars
        run: echo "name=tag::$(echo ${GITHUB_REF:10})" >> $GITHUB_OUTPUT
      - name: Show version
        run: echo ${{ steps.vars.outputs.tag }}
