name: Docker Image CI
on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Get the version
        id: vars
        # run: echo "name=tag::$(echo ${GITHUB_REF:10})" >> $GITHUB_OUTPUT
        run: echo "tag::$(echo ${GITHUB_REF:10})"
        shell: bash
      - name: Show version
        run: echo "tag=${{ steps.vars.outputs.tag }}"
        shell: bash
